id: e14c1cce957c43ea9b6f284af24580c0
initial_creation_type: ocr
source_metadata:
  volumes:
    1ce6cf0e331941d8865c104ab3f578fb:
      base_file: v015.txt
      image_group_id: I1PD95860
      title: ''
      total_pages: 1453
      volume_number: 15
